### ISSUE TITLE
Accept-Encoding request header is not respected

### ISSUE THREAD

**Issue by jtackaberry** [static-web-server/static-web-server#10]
After troubleshooting why fetching a file via `curl` or `wget` was corrupted, I realized it was merely gzipped.  The current behavior blindly gzips always.

Instead, it should only gzip when the client advertises support via an `Accept-Encoding` header.

**Comment by joseluisq** [comment]
Due to one built-in features which enables gzip by default. But it would be fine as well to support Accept-Encoding checking.

**Comment by jtackaberry** [comment]
Looks like a relatively simple matter to check the `Request` object in [`GzipMiddleware`](https://github.com/joseluisq/static-web-server/blob/v1.4.0/src/gzip.rs#L10) and skip it if `Accept-Encoding: gzip` isn't set?  Maybe it's deceptively simple. :)

BTW, does this compress the entire file in memory at once?  i.e. if you wanted to serve up a 2G file, would it require several GB of RAM to process?

**Comment by joseluisq** [comment]
> Looks like a relatively simple matter to check the `Request` object in [`GzipMiddleware`](https://github.com/joseluisq/static-web-server/blob/v1.4.0/src/gzip.rs#L10) and skip it if `Accept-Encoding: gzip` isn't set? Maybe it's deceptively simple. :)

Yes, it's a matter of just prepend one condition.

**Comment by joseluisq** [comment]
> BTW, does this compress the entire file in memory at once? i.e. if you wanted to serve up a 2G file, would it require several GB of RAM to process?

Gzip middleware is stream deflate-based compression. So your 2GB file size should be served in stream mode.

**Comment by joseluisq** [comment]
A RC `v1.5.0-rc1` will happen very soon in order to test the changes.

**Comment by joseluisq** [comment]
[v1.5.0](https://github.com/joseluisq/static-web-server/releases/tag/v1.5.0) released as well the Docker images.

**Comment by jtackaberry** [comment]
Tested (via Docker image) and confirmed fixed, as is #11.

Thanks very much, José!

**Comment by joseluisq** [comment]
You're welcome. :+1: 
Don't hesitate to contribute with feedback or PRs.
