### ISSUE TITLE
Support HEAD method

### ISSUE THREAD

**Issue by jtackaberry** [static-web-server/static-web-server#11]
Currently HEAD returns 405.

Please consider implementing this method.  It's quite useful for poking for the `Last-Modified` header before issuing ` GET`.

**Comment by joseluisq** [comment]
Verified, a new PR should happen in coming hours.

**Comment by joseluisq** [comment]
This issue was addresed via  https://github.com/joseluisq/iron-staticfile-middleware/pull/1.
So a RC `v1.5.0-rc1` will happen soon so you can test the changes.
