### ISSUE TITLE
Large files fail

### ISSUE THREAD

**Issue by ByronAP** [static-web-server/static-web-server#15]
Tested with a 10GB dummy file the server never begins the transfer. A connection is made but no data returned and nothing shown in console.

**Comment by joseluisq** [comment]
Unfortunately [Partial Content Delivery](https://en.wikipedia.org/wiki/Byte_serving) is not supported yet. For example iron/staticfile/pull/98 has some kind of progress but it got stuck.

I think probably a workaround should be to stick the server behind an Nginx instance and use Nginx to serve those big files.

**Comment by joseluisq** [comment]
FYI this feature is already implemented and will be released in coming days.

**Comment by joseluisq** [comment]
[v1.9.0](https://github.com/joseluisq/static-web-server/releases/tag/v1.9.0) released.
