### ISSUE TITLE
Add screenshots of the UI

### ISSUE THREAD

**Issue by NightMachinery** [static-web-server/static-web-server#21]

**Comment by joseluisq** [comment]
Can you provide more context to this issue? I don't really get it.

**Comment by NightMachinery** [comment]
I want to see the frontend this tool generates for browsing directory listings.

**Comment by joseluisq** [comment]
Directory browsing is not supported. Please see https://github.com/joseluisq/static-web-server#features

If you want it You can open a new issue and explain why that new feature.

**Comment by lukasa1993** [comment]
@joseluisq any way to add directory browsing or any approach ? i want to use this for my local server, i just want to see whats in folder and so i don't generate links manually

**Comment by joseluisq** [comment]
> @joseluisq any way to add directory browsing or any approach ? i want to use this for my local server, i just want to see whats in folder and so i don't generate links manually

Sure, feel free to open a new feature issue.

**Comment by joseluisq** [comment]
Feature released on latest [v1.14.0](https://github.com/joseluisq/static-web-server/releases/tag/v1.14.0)
Feedback welcome.

**Comment by lukasa1993** [comment]
> Feature released on latest [v1.14.0](https://github.com/joseluisq/static-web-server/releases/tag/v1.14.0)
> Feedback welcome.

how can it be enabled in docker ?

**Comment by joseluisq** [comment]
Just `-i=true` or `--directory-listing=true`
More info in README file. https://github.com/joseluisq/static-web-server/tree/1.x

**Comment by lukasa1993** [comment]
> Just `-i=true` or `--directory-listing=true`
> More info in README file. https://github.com/joseluisq/static-web-server/tree/1.x

yea i saw that but i am using your suggested docker-compose.yml file and not sure where to add it there

**Comment by joseluisq** [comment]
> yea i saw that but i am using your suggested docker-compose.yml file and not sure where to add it there

In your Docker file just use the equivalent env variable. `SERVER_DIRECTORY_LISTING=true`
Check the Readme

**Comment by joseluisq** [comment]
FYI all CLI flags have their equivalent env variables.

**Comment by lukasa1993** [comment]
> > yea i saw that but i am using your suggested docker-compose.yml file and not sure where to add it there
> 
> In your Docker file just use the equivalent env variable. `SERVER_DIRECTORY_LISTING=true`
> Check the Readme

thank you works well, any way to exclude `assets` folder ? or can i make that folder optional? 

if i just remove it

`[ERROR] - Assets directory path not found or inaccessible`

i get this error and it doesnt start

**Comment by joseluisq** [comment]
> thank you works well, any way to exclude `assets` folder ? or can i make that folder optional?

Not for now since I have introduced it for my own use cases on production and also programmed on early days of code base.
But I have plans to make it optional on v1. See  #17

One ugly workaround is just create an `assets` dir with one `index.html` inside. The directory listing feature looks always for a index.html in a directory. If it's found then the directory listing simply doesn't list your files.

**Comment by lukasa1993** [comment]
> > thank you works well, any way to exclude `assets` folder ? or can i make that folder optional?
> 
> Not for now since I have introduced for my own use cases on production also programmed on early days of code base.
> But I have plans to make it optional.
> 
> One ugly workaround is just create an `assets` dir with one `index.html` inside. The directory listing feature looks always for a index.html in a directory. If it's found then the directory listing simply don't list your files.

i think i found better solution, at-least inside docker, old docker volume trick

```
    environment:
      - SERVER_ASSETS=/assets
    volumes:
      - /assets
```

**Comment by joseluisq** [comment]
> i think i found better solution, at-least inside docker, old docker volume trick
> 
> ```
>     environment:
>       - SERVER_ASSETS=/assets
>     volumes:
>       - /assets
> ```

Yep, it's also fine via Docker.

**Comment by joseluisq** [comment]
FYI about make optional `assets` directory https://github.com/joseluisq/static-web-server/issues/17

On beta `v2` there is just a `root` dir but directory listing feature is missing.
