### ISSUE TITLE
Support for redirects from HTTP to HTTPS

### ISSUE THREAD

**Issue by HenningHolmDE** [static-web-server/static-web-server#25]
It is a common use case that a web server that delivers content as HTTPS also supports redirecting from the HTTP protocol (code 301).
While one could solve this with a second server instance or a proxy (such as nginx), it would be a great feature for static-web-server to support this as a built-in feature.
My proposal is to add a new command line switch (e.g. `--tls-redirect-from <port>`) that enables this behaviour.
I will implement this in a fork of the repository and if you are interested, I would be happy to provide a PR to merge it back upstream.

**Comment by joseluisq** [comment]
Sure, feel free to send a PR.
You can also take a look at https://github.com/joseluisq/iron-staticfile-middleware/blob/master/src/http_to_https_redirect.rs
This fork is used with this server.
