### ISSUE TITLE
react delivery

### ISSUE THREAD

**Issue by lukasa1993** [static-web-server/static-web-server#27]
can this be configured somehow so it serves index on any route? so it supports react like single site deployments

**Comment by joseluisq** [comment]
Custom routes are not supported since this is out of the scope (for now) of this server. Please see https://github.com/joseluisq/static-web-server/issues/23
However happy to receive PRs with proposals.

**Comment by joseluisq** [comment]
BTW Recently we merged https://github.com/joseluisq/static-web-server/pull/91 that it could maybe help with SPAs. See [the docs](https://sws.joseluisq.net/features/error-pages/#fallback-page-for-use-with-client-routers).
