### ISSUE TITLE
Support HSTS and turn on by default

### ISSUE THREAD

**Issue by tim-seoss** [static-web-server/static-web-server#39]
https web servers should support RFC 6797 "HTTP Strict Transport Security (HSTS)".

This should probably be on by default, and also default to a sensible time period (e.g. 2 years).  A command-line switch could optionally disable HSTS (e.g. `--hsts-seconds=0`).

https://www.globalsign.com/en/blog/what-is-hsts-and-how-do-i-use-it

**Comment by joseluisq** [comment]
Yeah, that's good idea since this normally tends to happen at proxy level.

**Comment by joseluisq** [comment]
Feature request released on [v2.0.0-beta.5](https://github.com/joseluisq/static-web-server/releases/tag/v2.0.0-beta.5)

**Comment by tim-seoss** [comment]
I'll check it out, thanks!
