### ISSUE TITLE
Issue with volume in unRAID

### ISSUE THREAD

**Issue by bergi9** [static-web-server/static-web-server#51]
First off, I don't know if it's an unRAID, Docker or the static-web-server issue. I'll post this issue in unRAID forum too.

The issue is that the static-web-server uses the `VOLUME ["/public"]` and I bind some paths into the container from unRAID which fails to umount when stopping the array. In unRAID it's called path as for the `-v /somedir:/public` argument and array manages the HDD mounting and shares. The shares in unRAID are located in `/mnt/user/<sharename>`.

I've bind 2 shared folder from unRAID into a subfolder in `/public`:
 - `/mnt/user/movies` to `/public/movies`
 - `/mnt/user/series` to `/public/series`

It's working fine so far until I want to shutdown the server or stop the array.
unRAID does these following steps:
 - stop containers graceful
 - stop docker
 - umount all shares
 - stop the array

Docker stops fine but umounting all the shares fails here because static-web-server uses `VOLUME ["/public"]` which creates a new volume by docker into `/var/lib/docker/volumes/<volume>/_data` and the both binds of `/public/movies` and `/public/series` are mounted into this folder. When docker stops the binds are not linked anymore still unRAID sees the binding between them and cannot umount the shares. To do the graceful shutdown I manually umounting both of the binds directly in the `/var/lib/docker/volumes/<volume>/_data_/movies`, kill `/dev/loop2` then unRAID is able to umount all `/mnt/user` shares.
https://github.com/joseluisq/static-web-server/blob/d165213f375b5394736c97d68b348818d79b2d4a/docker/scratch/Dockerfile#L18

If static-web-server wouldn't use `VOLUME ["/public"]` thus wouldn't create a volume under `/var/lib/docker/volumes/<volume>` and the bind goes directly into the docker process so that after stopping of docker no dead mounting exists.

**Comment by joseluisq** [comment]
Ok, I understand that the problem for your unRAID setup is because `VOLUME ["/public"]` creates an extra Docker volume that you wouldn't like to have because unRAID can not unmount it.

I believe that assuming an extra volume like `VOLUME ["/public"]` "could" be a tradeoff but the reason is because of the server defaults adopted early on by this project. In particular this one:

```sh
    -d, --root <root>
            Root directory path of static files [env: SERVER_ROOT=]  [default: ./public]
```

It defaults to `./public` which doesn't exist on a container like `static-web-server/docker/scratch/Dockerfile`.
"The logical" thing would be defaults to an already-directory in-place. But unfortunately is not the case.
However we could remove that volume instruction from the `Dockerfile` but it could break other users using the server defaults.

So it ​difficulties **at this stage of the game** to make the switch (not to do the removal which is easy).

**Workarounds/Solutions**

I'm thinking now that probably we could replace the current `VOLUME ["/public"]` with a `RUN mkdir /public` in order to avoid that Docker volume and see how it behaves. What do you think? Would that solve your problem? it would great if you can test it and let me know.

---

Clarifying also that I don't see this as an issue but more like a kind-of-feature or improvement if you want call it.

**Comment by bergi9** [comment]
Yes, I can test it.

So in your opinion it's not a bug of static-web-server but rather a bug in docker or unRAID if it couldn't umount the paths in the volume properly?

**Comment by joseluisq** [comment]
> So in your opinion it's not a bug of static-web-server but rather a bug in docker or unRAID if it couldn't unmount the paths in the volume properly?

I don't know if call it as a `static-web-server` bug itself since the `Dockerfile` behaves as intended.
I don't also see this is an unRAID or Docker issue however as I told you we can adjust it for suite your use case better.

It's more like configuration thing that it could be made.

**Comment by bergi9** [comment]
How about for testing purpose to push a docker image to hub with the tag `joseluisq/static-web-server:latest-novolume`? So that we can test it without bringing troubles to the users who already uses it.

**Comment by joseluisq** [comment]
> How about for testing purpose to push a docker image to hub with the tag `joseluisq/static-web-server:latest-novolume`? So that we can test it without bringing troubles to the users who already uses it.

Sure, I could publish that change so you could test it in your unRAID environment. Probably a `joseluisq/static-web-server:dev` image for that purpose.

**Comment by joseluisq** [comment]
May you share please a screenshot or log showing the extra Docker volume created and not possible to umount?

**Comment by joseluisq** [comment]
I did take it a closer look and it's possible to just remove `VOLUME ["/public"]` without issues.
It doesn't interfere with current functionality provided.

An enhancement PR should be come soon.
However  I will need your help with the testing and verification in your unRAID environment.

**Comment by bergi9** [comment]
> May you share please a screenshot or log showing the extra Docker volume created and not possible to umount?
On unRAID these volume will get created on `docker create`. Currently of all docker images I added the `static-web-server` is the only one who created these volumes under `/var/lib/docker/volumes/<random_volume_id_of_static_web_server>/_data`.

When I update the config of this docker image.
![grafik](https://user-images.githubusercontent.com/5556750/132258755-ea339fed-ecbc-4583-a148-d793d75e1763.png)

All these volumes belong to the `static-web-server` image.
![grafik](https://user-images.githubusercontent.com/5556750/132258786-2fa3a4d1-427e-419d-a77c-12b0fbc7332d.png)
![grafik](https://user-images.githubusercontent.com/5556750/132258841-97154149-82d4-4cd1-b283-403d24166e81.png)

About the umount issue I don't want do that anymore because it would trigger parity check on startup when not shutdown properly and delay the boot process. But testing it without `VOLUME ["/public"]` I would do it.

**Comment by joseluisq** [comment]
Great,
I'm publishing the Docker images for you can test.
Let's continue the testing discussion and results on the PR #52 .
