### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by dawidmachon** [static-web-server/static-web-server#60]
I would like to ask about the potential risks of using this image? Can other services(docker or local), on a clean, default machine (configuration) be compromised, does the configuration is also directed to be as secure as fast?

**Comment by joseluisq** [comment]
Can you please clarify in which case or circumstance can be the server compromised?

**Comment by joseluisq** [comment]
If you are looking for a more secure sandbox where to run `SWS` then you can do it for example via **systemd** (Linux), launchd (Macos) or another using _Socket Activation_ which is supported by `SWS` via the `-f, --fd` option.

You can get more context about it on https://github.com/joseluisq/static-web-server/issues/36#issue-866969484.

[The socket activation model](http://0pointer.de/blog/projects/socket-activation.html) is basically the alternative to TCP port binding.
And for `systemd`, there is a fully working example in this repository under the [./systemd](https://github.com/joseluisq/static-web-server/tree/master/systemd) directory.

**Comment by joseluisq** [comment]
Regarding security.
Recently I have published more friendly documentation about features like _`HTTP/2 + TLS`_  or _`File Descriptor Socket Passing`_. If you are interested have a look at the example on https://sws.joseluisq.net/

BTW I'm closing the issue. I think with previous comments I have answered your questions (I hope).
If you have other doubts just let me know.
